name: my-pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Code
        uses: actions/checkout@v3

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: '21.6.1'

      - name: Install Server Dependencies
        run: npm install
        working-directory: ./server
  
  test:
    runs-on: ubuntu-latest
    needs: build
  
    steps:
      - name: Check Code
        uses: actions/checkout@v3
  
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: '21.6.1'
  
      - name: Install Server Dependencies
        run: npm install
        working-directory: ./server
  
      - name: Run Test endpoint
        run: npm test
        working-directory: ./server
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: staging
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
  
      - name: Deploy to Staging
        run: |
          echo "running deployment scripts"
          echo "Application deployed "
  
  notify:
    runs-on: ubuntu-latest
    needs: deploy
  
    steps:
      - name: Notify Teams on Success
        if: success()
        run: |
          curl -H 'Content-Type: application/json' -d '{"text": "Deployment to staging succeeded"}' ${{ secrets.TEAMS_WEBHOOK_URL }}

      - name: Notify Teams on Failure
        if: failure()
        run: |
          curl -H 'Content-Type: application/json' -d '{"text": "Deployment to staging failed"}' ${{ secrets.TEAMS_WEBHOOK_URL }}        